# -----------------------------------------------#
#  _______             _____      _              #
# |__   __|           / ____|    | |             #
#    | |_ __ ___  ___| |    _   _| |_ ___ _ __   #
#    | | '__/ _ \/ _ \ |   | | | | __/ _ \ '__|  #
#    | | | |  __/  __/ |___| |_| | ||  __/ |     #
#    |_|_|  \___|\___|\_____\__,_|\__\___|_|     #
#                                                #
# -----------------------------------------------#

# TreeCuter by Norbit4

# github: https://github.com/Norbit4
# website: https://n0rbit.pl

# If you like the plugin, support me with a positive opinion on spigot.org, thanks! <3

#---------------------------------------#
#               [Config]                #
#---------------------------------------#

use-permissions: false
permission: 'treecuter.use'

max-tree-height: 20

shift-mining: true
accept-no-tools: false

# mining effect works only with shift-mining enabled!
apply-mining-effect: true
effect-level: 2

items-to-inventory: false

# automatically plants saplings that lie on the ground!
auto-plant: true

accept-tools:
  - 'WOODEN_AXE'
  - 'STONE_AXE'
  - 'IRON_AXE'
  - 'GOLDEN_AXE'
  - 'DIAMOND_AXE'
  - 'NETHERITE_AXE'

#  if you want to add a tree, you need to add leaf blocks and wood blocks.
#  probably trees available from mods will work too.

accept-wood-blocks:
  - 'OAK_LOG'
  - 'SPRUCE_LOG'
  - 'BIRCH_LOG'
  - 'JUNGLE_LOG'
  - 'ACACIA_LOG'
  - 'DARK_OAK_LOG'
  - 'MANGROVE_LOG'
  - 'MANGROVE_ROOTS'
  - 'CHERRY_LOG'

accept-leaves-blocks:
  - 'OAK_LEAVES'
  - 'SPRUCE_LEAVES'
  - 'BIRCH_LEAVES'
  - 'JUNGLE_LEAVES'
  - 'ACACIA_LEAVES'
  - 'DARK_OAK_LEAVES'
  - 'MANGROVE_LEAVES'
  - 'CHERRY_LEAVES'

auto-plant-saplings:
  - 'OAK_SAPLING'
  - 'SPRUCE_SAPLING'
  - 'BIRCH_SAPLING'
  - 'JUNGLE_SAPLING'
  - 'ACACIA_SAPLING'
  - 'DARK_OAK_SAPLING'
  - 'MANGROVE_PROPAGULE'
  - 'CHERRY_SAPLING'