#-------------------------------------------------#
#   _______             _____      _              #
#  |__   __|           / ____|    | |             #
#     | |_ __ ___  ___| |    _   _| |_ ___ _ __   #
#     | | '__/ _ \/ _ \ |   | | | | __/ _ \ '__|  #
#     | | | |  __/  __/ |___| |_| | ||  __/ |     #
#     |_|_|  \___|\___|\_____\__,_|\__\___|_|     #
#                                                 #
#-------------------------------------------------#

# TreeCuter by Norbit4

# github: https://github.com/Norbit4
# website: https://n0rbit.pl

# If you like the plugin, support me with a positive opinion, thanks! <3

#---------------------------------------#
#               [Config]                #
#---------------------------------------#

permission-message: '&cYou do not have permission to use this command!'

# if true, only players with permission can cut down trees
use-permissions: false
permission: 'treecuter.use'

# max blocks to cut at once
# only important for GIANT custom trees!
max-blocks: 100

# if true, the player must hold shift to cut down trees
shift-mining: true

# mining effect works only with shift-mining enabled!
apply-mining-effect: true
effect-level: 2

# if true, blocks that have been cut off, will glow
# [!] supports paper or forks versions: 1.17.1, 1.18.2, 1.19.4, 1.20.2
glowing-blocks: true
# colors: black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green
#         aqua, red, magenta, light_purple, yellow, white
glowing-color: 'red'

# cut blocks automatically go to player inventory
items-to-inventory: false

# automatically plants saplings that lie on the ground!
auto-plant: false

custom-tool:
  enable: false
  # material support ItemsAdder, when you use item from ItemsAdder, you must use 'ia:<ID>' instead of 'MATERIAL'
  # example: 'ia:example_item_id'
  material: 'NETHERITE_AXE'
  name: '&c&lGOD AXE'

#toogle messages
toggle:
  message-on: '&aEnabled &7cutting down trees!'
  message-off: '&cDisabled &7cutting down trees!'

# blocked worlds
block-worlds:
  - 'example_world'

accept-tools:
  - 'WOODEN_AXE'
  - 'STONE_AXE'
  - 'IRON_AXE'
  - 'GOLDEN_AXE'
  - 'DIAMOND_AXE'
  - 'NETHERITE_AXE'

accept-wood-blocks:
  - 'OAK_LOG'
  - 'SPRUCE_LOG'
  - 'BIRCH_LOG'
  - 'JUNGLE_LOG'
  - 'ACACIA_LOG'
  - 'DARK_OAK_LOG'
  - 'MANGROVE_LOG'
  - 'MANGROVE_ROOTS'
  - 'CHERRY_LOG'
  - 'OAK_WOOD'
  - 'SPRUCE_WOOD'
  - 'BIRCH_WOOD'
  - 'JUNGLE_WOOD'
  - 'ACACIA_WOOD'
  - 'DARK_OAK_WOOD'
  - 'MANGROVE_WOOD'
  - 'CHERRY_WOOD'

auto-plant-saplings:
  - 'OAK_SAPLING'
  - 'SPRUCE_SAPLING'
  - 'BIRCH_SAPLING'
  - 'JUNGLE_SAPLING'
  - 'ACACIA_SAPLING'
  - 'DARK_OAK_SAPLING'
  - 'MANGROVE_PROPAGULE'
  - 'CHERRY_SAPLING'