name: TreeCuter
version: '1.3.0'
main: pl.norbit.treecuter.TreeCuter
api-version: 1.17
author: Norbit4
website: 'https://n0rbit.pl'
softdepend:
  - Jobs
  - WorldGuard
commands:
  treecuter:
    permission: treecuter.admin
    aliases:
      - tc
    description: TreeCuter command
    usage: /treecuter [reload]