name: TreeCuter
version: '${version}'
main: pl.norbit.treecuter.TreeCuter
api-version: 1.17
author: Norbit4
website: 'https://n0rbit.pl'
softdepend:
  - WorldGuard
  - ItemsAdder
commands:
  treecuter:
    aliases:
      - tc
    description: TreeCuter main command.
    usage: /treecuter